### ISSUE TITLE
NGUI support...

### ISSUE THREAD

**Issue by D3m0n92** [YousicianGit/UnityNativeEdit#33]
I use NGUI and when i compile see in console: NullReferenceException on NativeEditBox.PrepareNativeEdit()

NativeEditBox.cs:217

**Comment by Hemaolle** [comment]
Hi @D3m0n92! You are welcome to implement NGUI support and submit a pull request. We don't have such a use case, so we won't be working on that.

**Comment by Nezz** [comment]
This only supports Unity UI
