### ISSUE TITLE
Splash screen not showing on Android

### ISSUE THREAD

**Issue by Hemaolle** [YousicianGit/UnityNativeEdit#43]
Apparently the workaround for Unity 5.6 problems of creating a custom `UnityPlayer` extensions that calls `setZOrderOnTop(false)` (https://github.com/YousicianGit/UnityNativeEdit/blob/da6f94b/src/androidProj/nativeeditplugin/src/main/java/com/bkmin/android/UnityPlayerNotOnTop.java#L20) messes with the Unity splash screen in some way so that a black screen is shown instead of the splash screen.

I'm not sure about the details as I didn't look into this myself yet, perhaps the splash screen is shown for part of the time or something like that.

In the https://github.com/YousicianGit/UnityNativeEdit/tree/fix/disableForUnity56 branch the plugin is disabled for Android if you still want to use it on iOS. Note that if you want to use that branch you should also not have an `AndroidManifest.xml` that would declare the `UnityPlayerActivityNotOnTop` as the main activity, since that change probably was what caused the problem.

**Comment by Hemaolle** [comment]
And indeed using the plugin with older Unity versions probably works still ok, but it's possible that the activity change will cause similar issues. It's not needed for older Unity versions though, so you can just go with the normal `UnityPlayerActivity`.

**Comment by Nezz** [comment]
It works fine for us with Unity 2017.4
